# 配置文件加密key
jasypt:
  encryptor:
    password: eapboot

server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eap_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    # ENC(F4B0s6u9xcDw3V+P0qC4CA==)
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        #login-password: ENC(F4B0s6u9xcDw3V+P0qC4CA==)
        login-password: root
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
      filter:
        stat:
          # 显示慢sql 默认当超过3秒显示
          log-slow-sql: true
    initialization-mode: always
    schema: classpath:db/eapboot-schema-demo.sql
    data: classpath:db/eapboot-data-demo.sql
  jpa:
    # 显示sql
    show-sql: true
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: none
  # Redis
  redis:
    host: 127.0.0.1
    password:
    # 数据库索引 默认0
    database: 0
    port: 6379
    # 超时时间 Duration类型 3秒
    timeout: 3S
  # Elasticsearch
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
  # 定时任务
  quartz:
    # 任务信息存储至数据库
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            misfireThreshold: 100
  # 工作流
  activiti:
    check-process-definitions: false
    db-identity-used: true
    # 自动生成Activiti相关表 第一次生成后建议关闭提高运行速度
    database-schema-update: true
    history-level: full
    # 扩展配置
    eapboot:
      # 流程图字体 默认宋体
      activityFontName: Microsoft YaHei
      labelFontName: Microsoft YaHei
  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    time-zone: GMT+8

eapboot:
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # token交互方式
  token:
    # 默认redis 设置为true后，token将存入redis，并具有单点登录功能 设为false将使用JWT交互
    redis: false
    # token中存储用户权限数据 设为true开启后可避免每次请求再获取用户权限，但有可能导致编辑权限菜单后无法读取到最新权限数据（需用户重新登录）
    storePerms: true
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10
  # ES
  elasticsearch:
    nodeClient: 127.0.0.1:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: false
  # mob api配置 mob官网注册申请即可
  mob:
    appKey: 你的appKey
  # 第三方社交登录配置
  social:
    # 前端回调登录地址
    callbackFeUrl: http://127.0.0.1:9999/login
    # 前端绑定账号回调地址
    callbackFeRelateUrl: http://127.0.0.1:9999/relate
    # github
    github:
      clientId: 你的clientId
      clientSecret: 你的clientSecret
      callbackUrl: http://127.0.0.1:8888/eapboot/social/github/callback
    # qq
    qq:
      appId: 你的appId
      appKey: 你的appKey
      callbackUrl: http://127.0.0.1:8888/eapboot/social/qq/callback
    # weibo
    weibo:
      appKey: 你的appKey
      appSecret: 你的appSecret
      callbackUrl: http://127.0.0.1:8888/eapboot/social/weibo/callback

# Actuator
management:
  health:
    status:
      http-mapping:
        DOWN: 200
        OUT_OF_SERVICE: 200
        FATAL: 200
        UNKNOWN: 200
    # 暂未用到ES 关闭其健康检查
    elasticsearch:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /eapboot/actuator/
      exposure:
        include: '*'

# 忽略鉴权url
ignored:
  urls:
    - /editor-app/**
    - /eapboot/act/**
    - /eapboot/dictData/getByType/**
    - /eapboot/email/sendResetCode
    - /eapboot/email/resetByEmail
    - /eapboot/file/view/**
    - /eapboot/social/**
    - /eapboot/ws/**
    - /eapboot/user/regist
    - /eapboot/user/smsLogin
    - /eapboot/user/resetByMobile
    - /eapboot/common/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /test/**

# Swagger界面内容配置
swagger:
  title: EapBoot API接口文档
  description: EapBoot Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://openea.org
  contact:
    name: Exrick
    url: http://openea.org
    email: xxxx@qq.com

# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

# 日志
logging:
  file: eapboot-logs/eapboot.log
